### ISSUE TITLE
Board Variants

### ISSUE THREAD

**Issue by The-Futurist** [4ms/stm32mp1-baremetal#29]
@danngreen 

Your docs refer to STM32MP157**A**-DK1 but that seems to be discontinued and there's a (newer?) [variant ](https://www.mouser.com/ProductDetail/STMicroelectronics/STM32MP157D-DK1?qs=zW32dvEIR3uOFdeAsko4%252BA%3D%3D)STM32MP157**D**-DK1 do think this will matter?

**Comment by danngreen** [comment]
I don't know but it's likely to work since so few board features are used.

**Comment by youngsea2000** [comment]
I use stm32mp157daax, no problem
